version: 2.1

orbs:
  # Replace this with your own!
  get-secret: oneriver/get-secret-manager@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.1.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:first"


jobs:
  get-secret-manager:
    docker:
    - image: cimg/base:2021.04
    steps:
    - checkout
    - run: echo <<pipeline.parameters.dev-orb-version>>
    - get-secret/get
        # secret-name : ci
        # output-path : env


workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148

      - bats/run:
          path: ./src/tests

      - orb-tools/publish-dev:
          orb-name: oneriver/get-secret-manager
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # - get-secret-manager
      - get-secret/test
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: oneriver/get-secret-manager
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - get-secret-manager
          filters:
            branches:
              only:
                - alpha
