version: 2.1

orbs:
  get-secret: oneriver/get-secret-manager@0.0.10

jobs:
  build:
    docker:
    - image: cimg/base:2021.04
    steps:
    - checkout
    - run: "echo 'print username'"
    - get-secret/get:
        secret-name : test-secret

workflows:
  main:
    jobs:
    - build