version: 2.1

orbs:
  get-secret: oneriver/get-secret-manager@0.0.13

jobs:
  build:
    docker:
    - image: cimg/base:2021.04
    steps:
    - checkout
    - get-secret/get:
        secret-name : ci

workflows:
  main:
    jobs:
    - build