version: 2.1

orbs:
  get-secret: oneriver/get-secret-manager@0.0.1

jobs:
  build:
    docker:
    - image: bash
    steps:
    - run: "echo 'print username'"
    - get-secret/get:
        # username: "oneriver"

workflows:
  main:
    jobs:
    - build