version: 2.1

orbs:
  get-secret: oneriver/get-secret@0.0.1

jobs:
  build:
    docker:
    - image: bash
    steps:
    - run: "echo 'print username'"
    - sample-orb/hello:
        username: "oneriver"

workflows:
  main:
    jobs:
    - build